# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemacontable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='cuenta',
        ),
        migrations.AddField(
            model_name='partida',
            name='cuenta',
            field=models.ManyToManyField(to='sistemacontable.Cuenta'),
        ),
    ]
