# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemacontable', '0002_auto_20181113_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=500)),
                ('monto', models.FloatField()),
            ],
            options={
                'verbose_name': 'Transaccion',
                'verbose_name_plural': 'Transacciones',
            },
        ),
        migrations.RemoveField(
            model_name='partida',
            name='monto',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemacontable.Partida'),
        ),
    ]
